import { IPOFormData, IPOAnalysisResult } from '../types/ipo';
import { runIPOAnalysis } from './scoring/scoringEngine';

export const DEMO_COMPANY_DATA: IPOFormData = {
  company: {
    name: 'ApexTech Solutions Ltd. (Demo Data)',
    sector: 'Technology',
    industry: 'Cloud Infrastructure & Enterprise Software',
    ipoPrice: 500,
    priceBandMin: 475,
    priceBandMax: 500,
    issueSize: 1500, // ₹ Cr
    listingExchange: 'NSE & BSE',
    openDate: '2026-10-12',
    closeDate: '2026-10-15',
    website: 'https://example-apextech.com',
    drhpUrl: 'https://example-apextech.com/drhp-prospectus.pdf',
  },
  financials: [
    {
      year: 'FY2022',
      revenue: 420,
      ebitda: 84,
      ebit: 68,
      pat: 48,
      eps: 4.8,
      operatingCashFlow: 52,
      freeCashFlow: 36,
      totalDebt: 45,
      netWorth: 210,
      totalAssets: 320,
      currentAssets: 180,
      currentLiabilities: 90,
      interestExpense: 4.0,
      roe: 22.8,
      roce: 24.1,
    },
    {
      year: 'FY2023',
      revenue: 560,
      ebitda: 118,
      ebit: 96,
      pat: 70,
      eps: 7.0,
      operatingCashFlow: 80,
      freeCashFlow: 58,
      totalDebt: 38,
      netWorth: 280,
      totalAssets: 410,
      currentAssets: 240,
      currentLiabilities: 115,
      interestExpense: 3.5,
      roe: 25.0,
      roce: 27.2,
    },
    {
      year: 'FY2024',
      revenue: 740,
      ebitda: 165,
      ebit: 138,
      pat: 102,
      eps: 10.2,
      operatingCashFlow: 120,
      freeCashFlow: 90,
      totalDebt: 30,
      netWorth: 380,
      totalAssets: 530,
      currentAssets: 310,
      currentLiabilities: 140,
      interestExpense: 3.0,
      roe: 26.8,
      roce: 29.5,
    },
    {
      year: 'FY2025',
      revenue: 980,
      ebitda: 230,
      ebit: 196,
      pat: 148,
      eps: 14.8,
      operatingCashFlow: 175,
      freeCashFlow: 135,
      totalDebt: 22,
      netWorth: 520,
      totalAssets: 710,
      currentAssets: 420,
      currentLiabilities: 180,
      interestExpense: 2.5,
      roe: 28.5,
      roce: 31.8,
    },
    {
      year: 'FY2026',
      revenue: 1280,
      ebitda: 315,
      ebit: 272,
      pat: 208,
      eps: 20.8,
      operatingCashFlow: 245,
      freeCashFlow: 195,
      totalDebt: 15,
      netWorth: 720,
      totalAssets: 950,
      currentAssets: 580,
      currentLiabilities: 220,
      interestExpense: 1.8,
      roe: 28.9,
      roce: 33.2,
    },
  ],
  valuation: {
    ipoPrice: 500,
    eps: 20.8,
    bookValuePerShare: 72.0,
    enterpriseValue: 4850,
    ebitda: 315,
  },
  peers: [
    {
      id: 'peer-1',
      name: 'CloudScale Technologies',
      pe: 32.5,
      pb: 8.4,
      evEbitda: 20.2,
      revenueGrowth: 22.0,
      patMargin: 15.5,
      roe: 24.0,
      roce: 26.0,
    },
    {
      id: 'peer-2',
      name: 'DataSphere Infoway',
      pe: 28.0,
      pb: 7.1,
      evEbitda: 18.0,
      revenueGrowth: 18.0,
      patMargin: 14.0,
      roe: 22.0,
      roce: 23.0,
    },
    {
      id: 'peer-3',
      name: 'CyberCore Systems',
      pe: 36.4,
      pb: 9.8,
      evEbitda: 23.5,
      revenueGrowth: 26.0,
      patMargin: 17.2,
      roe: 27.0,
      roce: 29.0,
    },
    {
      id: 'peer-4',
      name: 'NextGen Digital',
      pe: 26.5,
      pb: 6.5,
      evEbitda: 16.8,
      revenueGrowth: 16.0,
      patMargin: 13.0,
      roe: 19.0,
      roce: 21.0,
    },
  ],
  structure: {
    freshIssue: 1100, // ₹ Cr
    offerForSale: 400, // ₹ Cr
    debtRepayment: 15,
    capex: 620,
    workingCapital: 265,
    generalCorporate: 200,
  },
  marketData: {
    gmp: 85,
    gmpPercentage: 17.0,
    qibSubscription: 42.5,
    niiSubscription: 18.2,
    retailSubscription: 8.6,
    employeeSubscription: 3.4,
  },
  risks: {
    highDebt: 'no',
    negativeCashFlow: 'no',
    customerConcentration: 'yes', // Top 5 customers account for 38%
    supplierConcentration: 'no',
    regulatoryRisk: 'unknown',
    legalProceedings: 'no',
    promoterConcerns: 'no',
    highCompetition: 'yes',
    cyclicalBusiness: 'no',
    relatedPartyTransactions: 'no',
    dependenceOnKeyCustomers: 'yes',
    dependenceOnGovtPolicies: 'no',
    marginDecline: 'no',
    profitVolatility: 'no',
  },
};

export const DEMO_ANALYSIS_RESULT: IPOAnalysisResult = runIPOAnalysis(DEMO_COMPANY_DATA);

export const DEMO_COMPARISON_LIST: IPOFormData[] = [
  DEMO_COMPANY_DATA,
  {
    company: {
      name: 'Vanguard BioPharma Ltd. (Demo Data)',
      sector: 'Pharma',
      industry: 'Specialty Formulations & APIs',
      ipoPrice: 380,
      priceBandMin: 360,
      priceBandMax: 380,
      issueSize: 1200,
      listingExchange: 'NSE & BSE',
      openDate: '2026-11-04',
      closeDate: '2026-11-07',
    },
    financials: [
      {
        year: 'FY2023',
        revenue: 650,
        ebitda: 140,
        ebit: 115,
        pat: 82,
        eps: 9.1,
        operatingCashFlow: 95,
        freeCashFlow: 45,
        totalDebt: 90,
        netWorth: 410,
        totalAssets: 620,
        currentAssets: 340,
        currentLiabilities: 150,
        interestExpense: 8.5,
        roe: 20.0,
        roce: 22.0,
      },
      {
        year: 'FY2024',
        revenue: 780,
        ebitda: 175,
        ebit: 145,
        pat: 105,
        eps: 11.6,
        operatingCashFlow: 125,
        freeCashFlow: 60,
        totalDebt: 75,
        netWorth: 510,
        totalAssets: 730,
        currentAssets: 410,
        currentLiabilities: 170,
        interestExpense: 7.2,
        roe: 20.5,
        roce: 23.5,
      },
      {
        year: 'FY2025',
        revenue: 920,
        ebitda: 210,
        ebit: 176,
        pat: 128,
        eps: 14.2,
        operatingCashFlow: 160,
        freeCashFlow: 85,
        totalDebt: 60,
        netWorth: 630,
        totalAssets: 870,
        currentAssets: 490,
        currentLiabilities: 195,
        interestExpense: 5.5,
        roe: 20.3,
        roce: 24.2,
      },
    ],
    valuation: {
      ipoPrice: 380,
      eps: 14.2,
      bookValuePerShare: 70,
      enterpriseValue: 3400,
      ebitda: 210,
    },
    peers: [
      {
        id: 'peer-p1',
        name: 'Sun Pharma Peer A',
        pe: 34.0,
        pb: 6.2,
        evEbitda: 19.5,
        revenueGrowth: 13.0,
        patMargin: 16.0,
        roe: 18.0,
        roce: 20.0,
      },
      {
        id: 'peer-p2',
        name: 'Cipla Peer B',
        pe: 30.5,
        pb: 5.4,
        evEbitda: 17.2,
        revenueGrowth: 12.0,
        patMargin: 14.5,
        roe: 17.5,
        roce: 19.0,
      },
    ],
    structure: {
      freshIssue: 800,
      offerForSale: 400,
      debtRepayment: 60,
      capex: 520,
      workingCapital: 120,
      generalCorporate: 100,
    },
    marketData: {
      gmp: 42,
      gmpPercentage: 11.0,
      qibSubscription: 28.0,
      niiSubscription: 14.5,
      retailSubscription: 6.2,
    },
    risks: {
      highDebt: 'no',
      negativeCashFlow: 'no',
      customerConcentration: 'no',
      supplierConcentration: 'yes', // Active API supplier dependency
      regulatoryRisk: 'yes', // USFDA inspections
      legalProceedings: 'no',
      promoterConcerns: 'no',
      highCompetition: 'yes',
      cyclicalBusiness: 'no',
      relatedPartyTransactions: 'no',
      dependenceOnKeyCustomers: 'no',
      dependenceOnGovtPolicies: 'yes',
      marginDecline: 'no',
      profitVolatility: 'no',
    },
  },
  {
    company: {
      name: 'Bharat Solar & Power Ltd. (Demo Data)',
      sector: 'Energy',
      industry: 'Solar Module Manufacturing & EPC',
      ipoPrice: 220,
      priceBandMin: 205,
      priceBandMax: 220,
      issueSize: 2400,
      listingExchange: 'NSE & BSE',
      openDate: '2026-11-18',
      closeDate: '2026-11-21',
    },
    financials: [
      {
        year: 'FY2023',
        revenue: 1400,
        ebitda: 210,
        ebit: 160,
        pat: 85,
        eps: 7.0,
        operatingCashFlow: 140,
        freeCashFlow: -50,
        totalDebt: 980,
        netWorth: 680,
        totalAssets: 2100,
        currentAssets: 820,
        currentLiabilities: 650,
        interestExpense: 72,
        roe: 12.5,
        roce: 9.6,
      },
      {
        year: 'FY2024',
        revenue: 1950,
        ebitda: 310,
        ebit: 245,
        pat: 135,
        eps: 11.2,
        operatingCashFlow: 195,
        freeCashFlow: 20,
        totalDebt: 1120,
        netWorth: 815,
        totalAssets: 2650,
        currentAssets: 1050,
        currentLiabilities: 780,
        interestExpense: 88,
        roe: 16.5,
        roce: 12.6,
      },
      {
        year: 'FY2025',
        revenue: 2750,
        ebitda: 460,
        ebit: 375,
        pat: 215,
        eps: 17.9,
        operatingCashFlow: 280,
        freeCashFlow: -80,
        totalDebt: 1240,
        netWorth: 1030,
        totalAssets: 3400,
        currentAssets: 1380,
        currentLiabilities: 950,
        interestExpense: 95,
        roe: 20.8,
        roce: 16.5,
      },
    ],
    valuation: {
      ipoPrice: 220,
      eps: 17.9,
      bookValuePerShare: 85.8,
      enterpriseValue: 3880,
      ebitda: 460,
    },
    peers: [
      {
        id: 'peer-s1',
        name: 'Premier Solar Peer',
        pe: 25.0,
        pb: 3.8,
        evEbitda: 14.5,
        revenueGrowth: 30.0,
        patMargin: 8.5,
        roe: 19.0,
        roce: 15.0,
      },
      {
        id: 'peer-s2',
        name: 'Sterling Energy Peer',
        pe: 22.0,
        pb: 3.2,
        evEbitda: 13.0,
        revenueGrowth: 24.0,
        patMargin: 7.2,
        roe: 16.5,
        roce: 14.0,
      },
    ],
    structure: {
      freshIssue: 1800,
      offerForSale: 600,
      debtRepayment: 700,
      capex: 800,
      workingCapital: 200,
      generalCorporate: 100,
    },
    marketData: {
      gmp: 55,
      gmpPercentage: 25.0,
      qibSubscription: 54.0,
      niiSubscription: 32.0,
      retailSubscription: 14.2,
    },
    risks: {
      highDebt: 'yes', // High leverage for manufacturing capacity
      negativeCashFlow: 'no',
      customerConcentration: 'no',
      supplierConcentration: 'yes', // Polysilicon imports
      regulatoryRisk: 'yes', // Customs duty / ALMM mandates
      legalProceedings: 'no',
      promoterConcerns: 'no',
      highCompetition: 'yes',
      cyclicalBusiness: 'yes',
      relatedPartyTransactions: 'no',
      dependenceOnKeyCustomers: 'no',
      dependenceOnGovtPolicies: 'yes',
      marginDecline: 'no',
      profitVolatility: 'yes',
    },
  },
];
