import React from 'react';
import { ShieldAlert, FileText, AlertTriangle } from 'lucide-react';

export const TermsDisclaimerView: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-6">
      
      <div className="text-center space-y-2">
        <span className="text-xs font-bold uppercase tracking-wider text-rose-600 bg-rose-50 px-3 py-1 rounded-full border border-rose-200">
          LEGAL & REGULATORY COMPLIANCE
        </span>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight">
          Terms of Service & Regulatory Disclaimers
        </h1>
        <p className="text-xs sm:text-sm text-slate-600">
          Last updated: September 2026 • Please review these terms carefully before utilizing IPO360.
        </p>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200/90 shadow-sm p-6 sm:p-8 space-y-6 text-xs sm:text-sm text-slate-700 leading-relaxed">
        
        {/* Core Regulatory Box */}
        <div className="p-4 bg-amber-50/80 rounded-xl border border-amber-200/80 text-amber-950 space-y-2">
          <div className="flex items-center gap-2 font-bold text-amber-900">
            <AlertTriangle className="w-5 h-5 text-amber-700 flex-shrink-0" />
            <span>Not a SEBI Registered Investment Advisory</span>
          </div>
          <p className="text-xs leading-relaxed text-amber-900">
            IPO360 is NOT registered as a Research Analyst or Investment Advisor with the Securities and Exchange Board of India (SEBI), the US Securities and Exchange Commission (SEC), or any other financial regulatory body. The platform operates solely as a technological and mathematical tool for informational, educational, and analytical convenience.
          </p>
        </div>

        <div>
          <h3 className="text-base font-bold text-slate-900 mb-2">1. No Investment Advice or Buy/Sell Recommendations</h3>
          <p>
            Under no circumstances does IPO360 provide "BUY", "SELL", "ACCUMULATE", "SUBSCRIBE", or "AVOID" recommendations on any initial public offering, equity, debt, or derivative instrument. All scoring indicators, including the "IPO360 Score (out of 100)", the "Risk Meter", and category attributions, represent algorithmic mathematical evaluations strictly determined by user-provided financial figures and public prospectus filings.
          </p>
        </div>

        <div>
          <h3 className="text-base font-bold text-slate-900 mb-2">2. Unofficial Nature of Grey Market Premium (GMP)</h3>
          <p>
            Any Grey Market Premium (GMP), Kostak rate, or subjective sentiment metrics referenced within or entered into the platform reflect unofficial, unregulated, over-the-counter secondary expectations. GMP is highly volatile, subject to manipulation, and bears no guaranteed correlation with actual listing day prices or long-term capital compounding.
          </p>
        </div>

        <div>
          <h3 className="text-base font-bold text-slate-900 mb-2">3. Limitation of Liability</h3>
          <p>
            Equity markets carry inherent risk, including total loss of principal invested. Neither IPO360, its developers, researchers, nor affiliates shall be held liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your reliance on information generated by this platform. You agree to assume full responsibility for your financial decisions.
          </p>
        </div>

        <div>
          <h3 className="text-base font-bold text-slate-900 mb-2">4. User Responsibility to Review Official Offer Filings</h3>
          <p>
            All users must independently inspect the official Draft Red Herring Prospectus (DRHP) or Red Herring Prospectus (RHP) filed with the regulatory authorities (such as SEBI, BSE, and NSE) before making any financial commitment.
          </p>
        </div>

      </div>

    </div>
  );
};
